### ISSUE TITLE
Create an Air Mouse

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#11]
## AIM

Create an Air Mouse which allows you to control your Mouse Cursor using your Smartphone's Accelerator.

## Languages

- Python

## Details

You can make use of specific libraries like [Pynput](https://pythonhosted.org/pynput/mouse.html) and [Sockets](https://pypi.org/project/sockets/) to make your Smartphone function as an Air Mouse.

**Comment by seema1711** [comment]
Can I work on this?

**Comment by HarshCasper** [comment]
You have been assigned this Issue @seema1711

Please follow the general guidelines:

- Make a Branch off your Master and work on that.
- Make a proper README of how your Script works and what all libraries and modules you have used.
- Add Proper Comments and focus on Clean Code, in practice.
- Also, reference this Issue in your PR so that it becomes easy for us to review.

**Comment by HarshCasper** [comment]
Are you working on this @seema1711 ?

**Comment by seema1711** [comment]
I am but it's not working, Maybe you can assign it to someone else.

**Comment by HarshCasper** [comment]
You can try for some more time. Let me know if you need any help with this.

**Comment by seema1711** [comment]
I don't wanna hold up on this issue for long. Can you assign it to someone else?

**Comment by HarshCasper** [comment]
Sure @seema1711 🤗

**Comment by HarshCasper** [comment]
Assigned to @avinashkranjan

**Comment by Dhanush2612** [comment]
@vybhav72954 
Can you assign me this issue if its still up for grab?

**Comment by vybhav72954** [comment]
You are on roll!!!
@Dhanush2612 Assigned

**Comment by vybhav72954** [comment]
@Dhanush2612 Cause of plagiarism the PR has been shelved. Do you want to **actually** work on the script or not?

**Comment by Dhanush2612** [comment]
@HarshCasper 
I had attended a bootcamp related to ML, so all these stuff are what I did seeing their videos, so obviously for me to learn from them, they should have completed these projects right?

**Comment by vybhav72954** [comment]
@Dhanush2612 Taking inspiration and Plagiarising someone's content are two different things, my friend. I don't mind reusing code, but at least bring some personal touches to it, try to enhance it maybe. Am pretty sure whichever Bootcamp you attended never taught you to copy and paste a script.

If you want to learn with us, take simpler issues, try to solve them, rise and shine so that even we can say that this participant was the star of our project. This is not learning mate. I am sorry no appeals against plagiarism tags would be appreciated unless you either make a PR with your own genuine code.

Lastly I believe that you can actually produce good scripts, I trust you, you have the knowledge, make a new script here and we are good to go, the issue will remain assigned to you as of now (unless you don't want to).

**Comment by Dhanush2612** [comment]
@vybhav72954 
Thank you for your patience and explaining.
Can you please assign this to someone else?
I will work on improving issue #711.
Again thank you and sorry if I was rude.

**Comment by vybhav72954** [comment]
@Dhanush2612 Sure thing, am pretty sure you have another issue to work on, there are other open issues as well. Feel free to grab them anytime.

**Comment by HarshCasper** [comment]
@Dhanush2612 

Don't worry. We are here to support you. Plagiarism is not encouraged and this was the reason we closed the PR. We hope to see more of your contributions soon.
