### ISSUE TITLE
Discord Bot

### ISSUE THREAD

**Issue by sayan011** [HarshCasper/Rotten-Scripts#1299]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Describe the script

It is a cool and funny **discord bot**.which will help lonely people.

### Language

Python

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by HarshCasper** [comment]
Hi @sayan011 👋 

I don't think this falls in the category of a "script". It's more of a full-fledged application. Let me know what you think.

**Comment by ClasherKasten** [comment]
This issue is closed for the following reasons:
- this repository already contains a discord bot
- the existing discord bot will get removed through #1325
- as @HarshCasper mentioned, it is more of a full-fledged application than a script.

Anyway, thanks for the interest in the project and opening this issue for consideration.
