### ISSUE TITLE
script to automate a website

### ISSUE THREAD

**Issue by himanshu007-creator** [HarshCasper/Rotten-Scripts#695]
I would like to conrtibute by sharing code to automate a website.
The script can be run on CLI and VOILA,WEBSITE WILL OPEN!
please add DWOC label to it and assigne me this issue

**Comment by himanshu007-creator** [comment]
https://github.com/HarshCasper/Rotten-Scripts/pull/707 done sir. Kindly add DWOC label and level-3  tag to it.
Thank you!

**Comment by HarshCasper** [comment]
Level -3 Tag for a PR that has a few `echo` and `sleep` command? I'm sorry but the PR that has been raised is a shallow quality PR, and is not even fit to be reviewed and merged. Apart from that, I don't find the Issue to be worth taking up as well, since it has no functionality whatsoever. 

Thanks for making an Issue and a PR, but it is not fit to be carried forward!
