### ISSUE TITLE
RGB to Gray 

### ISSUE THREAD

**Issue by a-k-r-a-k-r** [HarshCasper/Rotten-Scripts#703]
**Description**
Simple to use GUI to convert RGB images to Gray scale images, using tkinter.

**Feature**
- Simple GUI
- easy to use
- convert and save image

**Labels**
- SWOC'20
- python
- tkinter
- Medium
- good first issue

**Comment by himanshu007-creator** [comment]
DONE https://github.com/HarshCasper/Rotten-Scripts/pull/712

**Comment by HarshCasper** [comment]
Hi @a-k-r-a-k-r 

Thanks for making this Issue! 

Unfortunately, we don't use GUI Apps since, as the Repo name is evident, we accept only Scripts that we can use from Terminal. If you would like to work on a Script version, you are more than welcome. 

@himanshu007-creator You are not allowed to take up any Issue and make a PR for the same, without explicit statement. Primarily because Issues created by Contributors are meant to be solved by them. I would be closing the PR https://github.com/HarshCasper/Rotten-Scripts/pull/712 because it follows no conventions laid down during Contribution.

**Comment by a-k-r-a-k-r** [comment]
Hi @HarshCasper thanks for the reply. I'm closing the issue for now.
