### ISSUE TITLE
Script to download Khan Academy Videos

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#807]
# Description

Create a Script to download videos from Khan Academy. The Script should be available with some default options like: 

- Downloading a Course by passing ahead the URL 
- Search the courses interactively and downloading them ahead
- Downloading all the courses all together 

You are free to have your own customization as part of it and come up with your own unique ideas.

## Language
- [X] Go
- [X] Javascript
- [X] Python

## Checklist:

- **Details on the Script**

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Khan Academy Downloader | Download Khan Academy Videos | Up-for-Grab, Hard, good first issue | |

**Comment by pganguli** [comment]
Since the current labels do not mention bash, I'm asking this; is it okay if this feature is implemented using bash scripting, that internally depends on the presence of the youtube-dl binary in $PATH ?

**Comment by HarshCasper** [comment]
I wanted this to be done the hard way :sweat_smile: 

No worries. You can still attempt it using BASH and can assume that youtube-dl binary is present.

**Comment by pganguli** [comment]
> I wanted this to be done the hard way sweat_smile
> 
> No worries. You can still attempt it using BASH and can assume that youtube-dl binary is present.

Even with the easy approach, it can get 'messy' pretty quickly :sweat_smile: .
Here's a half-ccoked script that scrapes their website for topics and prints out the sub-topics under them:
[ka.txt](https://github.com/HarshCasper/Rotten-Scripts/files/6076161/ka.txt)

Right now, I'm thinking of adding some more scraping logic to have it print out the titles of the links (instead of the barely readable link names themselves) in a menu-like fashion, which can be navigated as a hierarchy (topic -> subtopic -> video) by the user, and have youtube-dl download it.

If this approach seems okay, @HarshCasper you can assign this issue to me :)

**Comment by HarshCasper** [comment]
Looks awesome! 

We can review the approach once the PR is made. Everyone is open to take up any Issue they feel like.

**Comment by pganguli** [comment]
Thanks for the assignment. I should have a working version in about a week from now (let's say, 15th March). Polishing it might take a few more days.

**Comment by pganguli** [comment]
Can a maintainer please add the 'Assigned' tag? @HarshCasper @vybhav72954

**Comment by pganguli** [comment]
PR #839 raised. Since this issue has been assigned to me now, can a maintainer please add the "GSSOC'21" tag to both this issue and the linked PR? Thanks :)
